apiVersion: v1
kind: DeploymentConfig
metadata:
  name: wso2-mi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: wso2-mi
    spec:
      containers:
      - name: wso2mi-server
        image: 172.30.139.20:5000/wso2/wso2-mi:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 802
          fsGroup: 802
        ports:
        - containerPort: 8290
          protocol: TCP
        - containerPort: 8253
          protocol: TCP
        env:
          - name: AmdocsREST
            valueFrom:
              configMapKeyRef:
                name: backendurlamdocs
                key: AmdocsREST
          - name: MYSQL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mysqlusername
                key: MYSQL_USERNAME
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysqlpassword
                key: MYSQL_PASSWORD
          - name: MYSQL_SUREPAY_DB
            valueFrom:
              configMapKeyRef:
                name: mysqlsurepaydb
                key: MYSQL_SUREPAY_DB
          - name: PURCHASE_MANAGEMENT_SUREPAY_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: purchasemanagementsurepayendpoint
                key: PURCHASE_MANAGEMENT_SUREPAY_ENDPOINT
          - name: PURCHASE_MANAGEMENT_TRANSACTION_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: purchasemanagementtransactionendpoint
                key: PURCHASE_MANAGEMENT_TRANSACTION_ENDPOINT
          - name: PURCHASE_MANAGEMENT_GET_BALANCE_SELF_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: purchasemanagementgetbalanceselfendpoint
                key: PURCHASE_MANAGEMENT_GET_BALANCE_SELF_ENDPOINT
          - name: PURCHASE_MANAGEMENT_GET_BALANCE_OTHER_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: purchasemanagementgetbalanceotherendpoint
                key: PURCHASE_MANAGEMENT_GET_BALANCE_OTHER_ENDPOINT
          - name: AMDOCS_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: amdocsclientid
                key: AMDOCS_CLIENT_ID
          - name: AMDOCS_API_KEY
            valueFrom:
              configMapKeyRef:
                name: amdocsapikey
                key: AMDOCS_API_KEY
          - name: AMDOCS_ESB_USER_ENCODED_CREDS
            valueFrom:
             configMapKeyRef:
               name: amdocsesbuserencodedcreds
               key: AMDOCS_ESB_USER_ENCODED_CREDS
          - name: AmdocsSetEmailREST
            valueFrom:
              configMapKeyRef:
                name: amdocssetemailrest
                key: AmdocsSetEmailREST
        volumeMounts:
        - name: mi-conf-axis2
          mountPath: /home/wso2carbon/wso2-config-volume/conf/axis2/axis2.xml
          subPath: axis2.xml
      volumes:
      - name: mi-conf-axis2
        configMap:
          name: mi-conf-axis2
      - name: mi-conf-prop
        configMap:
          name: mi-conf-prop
      serviceAccountName: "wso2svc-acct"
